services:
  shardsvr1_1:
    container_name: shardsvr1_1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017
    ports:
      - "20001:27017"
    volumes:
      - sharding_mongodb_shardsvr1_1:/data/db
    networks:
      - sharding_mongodb_network

  shardsvr1_2:
    container_name: shardsvr1_2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017
    ports:
      - "20002:27017"
    volumes:
      - sharding_mongodb_shardsvr1_2:/data/db
    networks:
      - sharding_mongodb_network

  shardsvr1_3:
    container_name: shardsvr1_3
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017
    ports:
      - "20003:27017"
    volumes:
      - sharding_mongodb_shardsvr1_3:/data/db
    networks:
      - sharding_mongodb_network

volumes:
  sharding_mongodb_shardsvr1_1:
  sharding_mongodb_shardsvr1_2:
  sharding_mongodb_shardsvr1_3:

networks:
  sharding_mongodb_network:
    external: true