services:
  configsvr1:
    container_name: configsvr1
    image: mongo:latest
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017
    ports:
      - "10001:27017"
    volumes:
      - sharding_mongodb_configsvr1:/data/db
    networks:
      - sharding_mongodb_network

  configsvr2:
    container_name: configsvr2
    image: mongo:latest
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017
    ports:
      - "10002:27017"
    volumes:
      - sharding_mongodb_configsvr2:/data/db
    networks:
      - sharding_mongodb_network

  configsvr3:
    container_name: configsvr3
    image: mongo:latest
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017
    ports:
      - "10003:27017"
    volumes:
      - sharding_mongodb_configsvr3:/data/db
    networks:
      - sharding_mongodb_network

volumes:
  sharding_mongodb_configsvr1:
  sharding_mongodb_configsvr2:
  sharding_mongodb_configsvr3:

networks:
  sharding_mongodb_network:
    external: true