services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    platform: linux/amd64 # m4
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password57
      MYSQL_DATABASE: sample_db_57
      MYSQL_USER: user57
      MYSQL_PASSWORD: user_password57
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql57_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.conf:/etc/mysql/my.cnf

volumes:
  mysql57_data: