CREATE USER 'ndgndg91'@'%' IDENTIFIED BY 'ndgndg91';

GRANT RELOAD, FLUSH_TABLES ON *.* TO 'ndgndg91'@'%';
FLUSH PRIVILEGES;

GRANT SUPER, REPLICATION CLIENT ON *.* TO 'ndgndg91'@'%';
FLUSH PRIVILEGES;

GRANT REPLICATION SLAVE ON *.* TO 'ndgndg91'@'%';
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'ndgndg91'@'%';