services:
  cassandra-1:
    image: cassandra:4.0
    container_name: cassandra-1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra-1-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-2:
    image: cassandra:4.0
    container_name: cassandra-2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra-2-data:/var/lib/cassandra
    depends_on:
      cassandra-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-3:
    image: cassandra:4.0
    container_name: cassandra-3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra-3-data:/var/lib/cassandra
    depends_on:
      cassandra-2:
        condition: service_healthy

volumes:
  cassandra-1-data:
  cassandra-2-data:
  cassandra-3-data:
