services:
  redis:
    image: redis:7.4
    container_name: redis7.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data: