name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: docker tag
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./alpine-corretto21
        file: ./alpine-corretto21/Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/ndgndg91/giri-alpine-corretto21:${{ inputs.version }}
        push: true